# Generated by Django 4.1 on 2022-11-16 01:04

from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('data', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=userapp.models.filepath)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to=userapp.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='savemsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=50)),
                ('usub', models.CharField(max_length=50)),
                ('umsg', models.CharField(max_length=50)),
            ],
        ),
    ]
